### ISSUE TITLE
Pointer-10 K dataset

### ISSUE THREAD

**Issue by lei-sheng** [DrawZeroPoint/VectorDetectionNetwork#2]
Mr.Dong, it's sorry to bother you,  I am researching  meter reading recognition currently, and I hope to get your Pointer-10 K dataset, looking forward to your reply,Thank you very much.

**Comment by DrawZeroPoint** [comment]
Hi @lei-sheng, we are glad that you are interested in our work. The link to the dataset has just been made public. Please see README for details.
